#!/usr/bin/env python

import sys

from basestation_gui_python.Gui import BasestationGuiPlugin, MessagePlugin
from rqt_gui.main import Main
import pdb

plugin = 'rqt_basestation_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
